### ISSUE TITLE
Node set up help

### ISSUE THREAD

**Issue by debasish22** [strangelove-ventures/noble#114]
Can we do the noble node set up using docker ?

Any specific community where we can post our queries .

**Comment by boojamya** [comment]
Hi @debasish22, we have noble hooked up to our Heighliner repository which builds locked down images of many chain binaries. I recommend using that image.
https://github.com/strangelove-ventures/noble/pkgs/container/noble

No public discord has been setup yet.

**Comment by boojamya** [comment]
Closing this issue. 
We've created https://github.com/strangelove-ventures/noble-networks as a hub for network info.
