### ISSUE TITLE
Write interchain test for `Burn on Noble → Mint on Ethereum` use case.

### ISSUE THREAD

**Issue by jonathanpberger** [strangelove-ventures/noble#226]

**Comment by jonathanpberger** [comment]
https://www.notion.so/strangeloveventures/Noble-CCTP-rev-3-8b3064b246914348a506abb8817380ad?pvs=4#fac8ed2dafdb4bca8e15b525f5ecf686

**Comment by boojamya** [comment]
https://github.com/strangelove-ventures/noble-cctp-private-builds/blob/development/interchaintest/cctp_noble_dep_for_burn_test.go
