### ISSUE TITLE
Support for CosmWasm

### ISSUE THREAD

**Issue by rajeshn76** [strangelove-ventures/noble#228]
Is there plan to add support for CosmWasm into Noble? How can we use IBC (ex: cw20-ics20 smart contract) to transfer tokens from Noble chain to a CosmWasm smart contract chain?

**Comment by bd21** [comment]
Hey @rajeshn76, Noble is not a smart contract platform and there are no plans to add CosmWasm support.  Tokens issued from Noble are native (not cw20).

You can perform an ICS-20 token transfer using a wallet like Keplr or the cli: `nobled tx ibc-transfer transfer [src-port] [src-channel] [receiver] [amount]`
