### ISSUE TITLE
E2E Testing for testnet

### ISSUE THREAD

**Issue by bd21** [strangelove-ventures/noble#230]
This is ensure that the happy paths for each of the major APIs are working.

- [ ] Integrate newest versions of CCTP, Router (keep private)
- [ ] Wrapper contract deployed on Goerli
- [ ] Mock attestation service
- [ ] CCTP Relayer deployed

APIs to test (all originating from Ethereum)

send_message
send_message_with_caller
replace_message
replace_deposit_for_burn
deposit_for_burn
deposit_for_burn_with_caller
receive_message

**Comment by akc2267** [comment]
missing e2e tests from noble --> eth
