### ISSUE TITLE
Update to SDK v0.47 + IBC-Go v7

### ISSUE THREAD

**Issue by boojamya** [strangelove-ventures/noble#231]

**Comment by akc2267** [comment]
@johnletey when you have bandwidth can you advise?

**Comment by akc2267** [comment]
This should follow the CCTP launch

**Comment by akc2267** [comment]
potentially jump to ibc v8 and sdk v50

**Comment by jonathanpberger** [comment]
@agouin sez "Informal is handling this." Closing ticket.
