### ISSUE TITLE
Submit proposal to add `noble` to ICS Testnet

### ISSUE THREAD

**Issue by boojamya** [strangelove-ventures/noble#84]
Need assistance from testnet runners to assure a "yes" vote as voting period is only 60s.

**Comment by danbryan** [comment]
adding to the sprint so it shows up on my kanban board

**Comment by danbryan** [comment]
Staged here, will need update/create endpoints when infra has been completed.
Also, need to verify genesis/binary checsums on the day we submit the proposal.

https://github.com/strangelove-ventures/cosmos-testnets/tree/master/replicated-security/noble-1

**Comment by boojamya** [comment]
Made some updates here:
https://github.com/strangelove-ventures/cosmos-testnets/pull/1

Todo:
- [ ] add other testnet validator addresses to the auth/accounts object (just like what was done in above PR) (may need to de-code and re-endcode address)
- [ ] tag new release of noble
- [ ] rebuild binary and update hash and path in https://github.com/strangelove-ventures/cosmos-testnets/tree/master/replicated-security/noble-1

**Comment by danbryan** [comment]
Based on a conversation with Jehan, he advised that we wait until after the slasher chain and neutron launch if we want support from Hypha for launching noble.  I plan to follow up with dante on monday to confirm if this is the case, and what dates we could technically launch with or without their suport.

**Comment by jtieri** [comment]
i think it's safe to say that this can be closed now
